server:
  port: 6601
spring:
  application:
    name: weike-study-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.111.9:33306/admin_auth?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://39.107.111.9:6866/eureka/
  instance:
      prefer-ip-address: true    
